### ISSUE TITLE
GPIOMEM doesn't play well with SYSFS

### ISSUE THREAD

**Issue by jdtsmith** [n8henrie/node-rcswitch-gpiomem#5]
It appears that if you enable other GPIO-based homebridge plugins (like [homebridge-gpio-wpi2](https://github.com/rsg98/homebridge-gpio-wpi2)) which use `SYSFS` for pin _input_ (on completely different pins), this defeats n-r-g's ability to control the transmitter.  With h-g-wpi2 enabled: doesn't work.  Without: does work.

Is this a known issue?  Is there any interaction between the export functionality of `sysfs` and gpiomem?

**Comment by n8henrie** [comment]
Huh, no idea. You're the first to report -- I'll experiment in the next few days and get back to you.

Thanks for the ?bug report.

**Comment by n8henrie** [comment]
For other readers, @jdtsmith has a detailed post reviewing his findings on this issue in the other repo: https://github.com/n8henrie/homebridge-rcswitch-gpiomem/issues/11
